Traceback (most recent call last):
  File "/Users/takepy/takeoxdna/kakenhievolvedna2/oxdna_run/main.py", line 499, in <module>
    sys.exit(main(sys.argv))
  File "/Users/takepy/takeoxdna/kakenhievolvedna2/oxdna_run/main.py", line 486, in main
    start, end = make_output(data, output_folder, output_ATGC_folder)
  File "/Users/takepy/takeoxdna/kakenhievolvedna2/oxdna_run/main.py", line 410, in make_output
    length_dict= get_ab_length(data) ## TODO: Not compatible with L3
  File "/Users/takepy/takeoxdna/kakenhievolvedna2/oxdna_run/main.py", line 47, in get_ab_length
    length_a = int(re.sub(r"\D", "", length_a_str))#13
UnboundLocalError: local variable 'length_a_str' referenced before assignment
